
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTICOMMENT = 36;
  public static final int LEFTBRACKET = 29;
  public static final int DISPLAY = 2;
  public static final int PERIOD = 38;
  public static final int RIGHTBRACKET = 30;
  public static final int LPAREN = 24;
  public static final int INT = 18;
  public static final int PRINTLN = 17;
  public static final int MINUS = 21;
  public static final int STATIC = 3;
  public static final int RPAREN = 25;
  public static final int AND = 37;
  public static final int RIGHTCURLYBRACKET = 28;
  public static final int SEMICOLON = 26;
  public static final int RIGHTANGLEBRACKET = 32;
  public static final int COMMA = 31;
  public static final int CLASS = 7;
  public static final int PLUS = 20;
  public static final int MAIN = 5;
  public static final int IF = 8;
  public static final int THIS = 11;
  public static final int MULTIPLIES = 23;
  public static final int EOF = 0;
  public static final int BOOLEAN = 19;
  public static final int RETURN = 12;
  public static final int TRUE = 13;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int EXCLAIMATION = 39;
  public static final int BECOMES = 22;
  public static final int VOID = 4;
  public static final int ELSE = 9;
  public static final int WHILE = 10;
  public static final int PUBLIC = 6;
  public static final int STRING = 16;
  public static final int LEFTCURLYBRACKET = 27;
  public static final int LEFTANGLEBRACKET = 33;
  public static final int FALSE = 14;
  public static final int INTEGER_LITERAL = 35;
  public static final int IDENTIFIER = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DISPLAY",
  "STATIC",
  "VOID",
  "MAIN",
  "PUBLIC",
  "CLASS",
  "IF",
  "ELSE",
  "WHILE",
  "THIS",
  "RETURN",
  "TRUE",
  "FALSE",
  "NEW",
  "STRING",
  "PRINTLN",
  "INT",
  "BOOLEAN",
  "PLUS",
  "MINUS",
  "BECOMES",
  "MULTIPLIES",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "LEFTCURLYBRACKET",
  "RIGHTCURLYBRACKET",
  "LEFTBRACKET",
  "RIGHTBRACKET",
  "COMMA",
  "RIGHTANGLEBRACKET",
  "LEFTANGLEBRACKET",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "MULTICOMMENT",
  "AND",
  "PERIOD",
  "EXCLAIMATION"
  };
}

